### ISSUE TITLE
请问要怎么操作USB

### ISSUE THREAD

**Issue by lengyao88** [nivalxer/MobileDevice#1]

**Comment by nivalxer** [comment]
USB部分目前只实现了端口映射，可以参考我开源的另一个端口映射工具。可以映射任意iPhone上面的端口到本机

2016-03-17 16:35 GMT+08:00 lengyao <notifications@github.com>:

> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/nivalxer/MobileDevice/issues/1>
>



-- 
Nival、Xer
