### ISSUE TITLE
BatteryCurrentCapacity issue

### ISSUE THREAD

**Issue by semmikabel** [nivalxer/MobileDevice#2]
I tried to read the battery status by adding the following code into iOSDevice.cs:

`private string BatteryCurrent = string.Empty;`

and:

`        public string BatteryCurrentCapacity
        {
            get
            {
                if (this.BatteryCurrent.Length == 0)
                {
                    object deviceValue = this.GetDeviceValue(DeviceInfoKey.BatteryCurrentCapacity);
                    if (deviceValue != null)
                    {
                        this.BatteryCurrent = deviceValue.ToString();
                    }
                }
                return this.BatteryCurrent;
            }
        }`

Then I tried to read it to my lable with:

`lblBatteryStatus.Text = currentiOSDevice.BatteryCurrentCapacity;`

But there is no info, nothing. Same as for AppleID, doesn't show anything. Any help?

**Comment by nivalxer** [comment]
I add new funcation BatteryCurrentCapacity().
You can use this funcation to get BatteryCurrentCapacity.
Thanks for your feedback.

**Comment by semmikabel** [comment]
Cool will give that a try, thankyou for your quick response. Good work :)

**Comment by semmikabel** [comment]
It is working, thankyou. What about the CycleCount? Tried to load that in the same way you've done with com.apple.mobile.battery, but always get nothing or -1.

**Comment by nivalxer** [comment]
I haven't found any API to get CycleCount at the moment.
I'll keep looking.

**Comment by semmikabel** [comment]
There are a few other API's on Github than can get the CycleCount, but they export it to an PLIST and then read out each line. I believe it was MK.MobileDevice or something like that. 

Strange it doesn't read anything by just the domain of the battery and the CycleCount key.

**Comment by nivalxer** [comment]
Thanks.
MK.MobileDevice use iMobileDevice(C++) to get information.They use diagnostic service.
I'll add diagnostic service and try to get information.

**Comment by nivalxer** [comment]
@semmikabel 
I add new funcation GetBatteryInfoFormDiagnostics().
You can use this funcation to get FullChargeCapacity,DesignCapacity,CycleCount and Status.

**Comment by semmikabel** [comment]
You are amazing! Will give it a try later today, thankyou :).

**Comment by semmikabel** [comment]
I tried to find out how to use the GetBatteryInfoFormDiagnostics() function with Dictionary, but I don't get it work yet. Do you have an example on how to call for sample the Cyclecount?

**Comment by nivalxer** [comment]
:)

**Comment by yashsharma45** [comment]
Hello,

I tried to get Battery Cycle Count from Upper Diagnostic code which you provided. But it gives me Error.

System.AccessViolationException: 'Attempted to read or write protected memory. This is often an indication that other memory is corrupt.'

this Error Occured in ManagedTypeFromCFType Method in CoreFoundation File. Can you please tell me why it is occuring in my code??

Thanks in Advance
