### ISSUE TITLE
请问如何才能做到用AirTrafficHost.dll来同步铃声呢?

### ISSUE THREAD

**Issue by Kanong017** [nivalxer/MobileDevice#3]

**Comment by nivalxer** [comment]
@Kanong017 这部分功能暂时还没做，同步机制相对复杂一点儿，后期会更新这部分机制

**Comment by Kanong017** [comment]
@nivalxer 谢谢,请问你有联系方式吗?对于itunesmobiledevice库有一些疑问想问问您!

**Comment by nivalxer** [comment]
@Kanong017 新浪微博@NivalXer 发私信即可
